# Pandas 2: Mutate - Template File

Renaming and Removing Fields

- Clean-up field names by making them lowercase and replacing spaces with underscores
- Change employee nme to name
- Remove id field

In [ ]:
import pandas as pd
import numpy as np

# Create sample data
df_raw = pd.DataFrame({
    'employee ID': [101, 102, 103, 104],
    'Employee Nme': [' Emma  ', 'James', 'Sofia', 'Michael'],
    'department': ['Engineering', 'Marketing', 'Sales', 'HR'],
    'salary': [75000, 65000, 58000, 72000],
    'hobby': ['Reading', None, 'Travel', 'Sports'],
    'age': [29, 34, 28, 41]
})

# Make a copy of the raw data to work with. This way we preserve the original.
df = df_raw.copy()

# Add new commands here!

df

      name   department  salary    hobby  age
0   Emma    Engineering   75000  Reading   29
1    James    Marketing   65000     None   34
2    Sofia        Sales   58000   Travel   28
3  Michael           HR   72000   Sports   41

Add new fields 

- Add an employer field that is equal to Acme Corp for all employees
- Add a field is_high_earner that is True if salary is greater than or equal to 70000, otherwise False
- Strip empty spaces from the employee name field
- Create a new decade_age field that contains the decade of the employee's age (e.g., 20s, 30s, etc.)
- Set any employees in the HR department to have a bonus of 1000, all others get 500
- Create a new total_compensation field that is the sum of salary and bonus
- Fill in any null values in the hobby field with 'Not Specified'
- Create a new field full_info that combines employee name and department in the format "Name (Department)"
- Create a new field age_group that categorizes employees as 'Young' (under 30), 'Mid-career' (30-50), or 'Senior' (over 50) based on their decade_age field (using a dictionary and the map operation)

In [ ]:
age_map_dictionary = {


}

df = df.assign(
)

df

,name,department,salary,hobby,age,employer,is_high_earner,decade_of_age,bonus,total_compensation,full_info,age_group
0,Emma,Engineering,75000,Reading,29,Acme,True,20,500,75500,Emma (Engineering),Young
1,James,Marketing,65000,Not Specified,34,Acme,False,30,500,65500,James (Marketing),Mid-career
2,Sofia,Sales,58000,Travel,28,Acme,False,20,500,58500,Sofia (Sales),Young
3,Michael,HR,72000,Sports,41,Acme,True,40,1000,73000,Michael (HR),Mid-career